[package]
name = "oilwell-converter"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
oilwell-core = { path = "../crates/oilwell-core" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
rfd = "0.15"
