use spatial_types::{Point3,SpatialError};
#[derive(Debug,Clone,PartialEq)]pub struct TriangleMesh{pub vertices:Vec<Point3>,pub triangles:Vec<[u32;3]>}
impl TriangleMesh{
pub fn from_obj(text:&str)->Result<Self,SpatialError>{let mut v=Vec::new();let mut f=Vec::new();for (i,line) in text.lines().enumerate(){let t=line.trim();if let Some(rest)=t.strip_prefix("v "){let c:Vec<_>=rest.split_whitespace().collect();if c.len()<3{return Err(parse(i,"OBJ vertex requires xyz"));}v.push(point(&c,i)?);}else if let Some(rest)=t.strip_prefix("f "){let ids:Result<Vec<u32>,_>=rest.split_whitespace().map(|x|x.split('/').next().unwrap_or("").parse::<u32>().map(|n|n-1)).collect();let ids=ids.map_err(|_|parse(i,"invalid OBJ face"))?;for k in 1..ids.len().saturating_sub(1){f.push([ids[0],ids[k],ids[k+1]]);}}}finish(v,f)}
pub fn from_off(text:&str)->Result<Self,SpatialError>{let mut l=text.lines().map(str::trim).filter(|x|!x.is_empty()&&!x.starts_with('#'));if l.next()!=Some("OFF"){return Err(parse(0,"missing OFF signature"));}let h:Vec<_>=l.next().ok_or_else(||parse(1,"missing OFF counts"))?.split_whitespace().collect();let nv=h.first().ok_or_else(||parse(1,"missing vertex count"))?.parse::<usize>().map_err(|_|parse(1,"invalid vertex count"))?;let nf=h.get(1).ok_or_else(||parse(1,"missing face count"))?.parse::<usize>().map_err(|_|parse(1,"invalid face count"))?;let mut v=Vec::with_capacity(nv);for i in 0..nv{let c:Vec<_>=l.next().ok_or_else(||parse(i+2,"missing OFF vertex"))?.split_whitespace().collect();v.push(point(&c,i+2)?);}let mut f=Vec::new();for i in 0..nf{let c:Vec<_>=l.next().ok_or_else(||parse(i+2+nv,"missing OFF face"))?.split_whitespace().collect();let n=c.first().ok_or_else(||parse(i,"invalid OFF face"))?.parse::<usize>().map_err(|_|parse(i,"invalid OFF face"))?;let ids:Result<Vec<u32>,_>=c.iter().skip(1).take(n).map(|x|x.parse()).collect();let ids=ids.map_err(|_|parse(i,"invalid OFF index"))?;for k in 1..ids.len().saturating_sub(1){f.push([ids[0],ids[k],ids[k+1]]);}}finish(v,f)}
pub fn from_ascii_stl(text:&str)->Result<Self,SpatialError>{let mut v=Vec::new();let mut f=Vec::new();let mut tri=Vec::new();for (i,line) in text.lines().enumerate(){if let Some(rest)=line.trim().strip_prefix("vertex "){let c:Vec<_>=rest.split_whitespace().collect();tri.push(point(&c,i)?);if tri.len()==3{let base=v.len() as u32;v.extend(tri.drain(..));f.push([base,base+1,base+2]);}}}finish(v,f)}
pub fn to_obj(&self)->String{let mut o=String::new();for p in &self.vertices{o.push_str(&format!("v {} {} {}\n",p.0.x,p.0.y,p.0.z));}for t in &self.triangles{o.push_str(&format!("f {} {} {}\n",t[0]+1,t[1]+1,t[2]+1));}o}
}
fn point(c:&[&str],line:usize)->Result<Point3,SpatialError>{if c.len()<3{return Err(parse(line,"expected xyz"));}let n=|i:usize|c[i].parse::<f64>().map_err(|_|parse(line,"invalid coordinate"));Point3::new(n(0)?,n(1)?,n(2)?)}
fn parse(line:usize,message:&str)->SpatialError{SpatialError::Parse{line:line+1,message:message.into()}}
fn finish(vertices:Vec<Point3>,triangles:Vec<[u32;3]>)->Result<TriangleMesh,SpatialError>{if vertices.is_empty(){Err(SpatialError::Degenerate("mesh has no vertices"))}else{Ok(TriangleMesh{vertices,triangles})}}
#[cfg(test)]mod tests{use super::*;#[test]fn obj_triangulates_polygon(){let m=TriangleMesh::from_obj("v 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4\n").unwrap();assert_eq!(m.triangles.len(),2);}#[test]fn reads_ascii_stl(){let m=TriangleMesh::from_ascii_stl("solid a\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 0 1 0\nendloop\nendfacet\nendsolid\n").unwrap();assert_eq!(m.triangles.len(),1);}}
