#[test]
fn frontend_has_a_usable_entry_point() {
    let html = include_str!("../public/index.html");

    assert!(html.contains("<aside id=\"sidebar\""));
    assert!(html.contains("<main id=\"canvas-container\""));
    assert!(!html.contains("id=\"emptyState\""));
    assert!(html.contains("/api/health"));
    assert!(html.contains("id=\"pointCloudToMeshBtn\""));
    assert!(html.contains("id=\"meshToPointCloudBtn\""));
    assert!(html.contains("function ensurePlanarUvs"));
    assert!(html.contains("new ResizeObserver(onWindowResize).observe(viewport)"));
    assert!(html.contains("JSZip.loadAsync(file)"));
    assert!(html.contains("accept=\".glb,.gltf,.obj,.ply,.stl,.zip\""));
    assert!(html.contains("manager.setURLModifier"));
    assert!(html.contains("new MTLLoader(manager)"));
    assert!(html.contains("currentTexture || geom.userData.texture"));
    assert!(html.contains("function classifyGeometry"));
    assert!(html.contains("/api/point-cloud-analyze"));
    assert!(html.contains("/api/flat-surface-correct"));
    assert!(html.contains("/api/mesh-smooth"));
    assert!(html.contains("/api/model-floorplan-recognize"));
    assert!(html.contains("function geometryPlyBlob"));
    assert!(html.contains("function renderFloorplanLayout"));
    assert!(html.contains("function applyRustTransform"));
    assert!(html.contains("function transferSmoothedPositions"));
    assert!(html.contains("id=\"correctFlatSurfaceBtn\""));
    assert!(html.contains("id=\"recognizeModelFloorplanBtn\""));
    assert!(html.contains("function taubinSmoothGeometry"));
    assert!(html.contains("function centerAndGroundGeometry"));
    assert!(html.contains("function alignLongestAxis"));
    assert!(html.contains("function getLoadedGeometryMode"));
    assert!(html.contains(
        "Loaded data mixes mesh and point-cloud layers. Isolate one mode before converting."
    ));
    assert!(html.contains("function getActiveTexture"));
    assert!(html.contains("function ensureTexturePixels"));
    assert!(html.contains("function sceneMetadataPayload"));
    assert!(html.contains("function rememberSceneAnalysis"));
    assert!(html.contains("function renderSceneAnalysisOverlay"));
    assert!(html.contains("function clearSceneAnalysisOverlay"));
    assert!(html.contains("function updateContextHelp"));
    assert!(html.contains("async function buildModelPackage"));
    assert!(html.contains("reference_images: {"));
    assert!(html.contains("references/photos/${index + 1}_"));
    assert!(html.contains("id=\"refinePackageImagesBtn\""));
    assert!(html.contains("async function refinePackageTexture"));
    assert!(html.contains("/api/image-assisted-refinement"));
    assert!(html.contains("class=\"nested-accordion\""));
    assert!(html.contains("Import geometry or package"));
    assert!(html.contains("id=\"packageImportReview\""));
    assert!(html.contains("id=\"packageModelSelect\""));
    assert!(html.contains("async function inspectZipPackage"));
    assert!(html.contains("/api/v1/projects/import-package"));
    assert!(html.contains("async function loadCommittedRustPackage"));
    assert!(html.contains("Recognition"));
    assert!(html.contains("Room plan"));
    assert!(html.contains("Working package"));
    assert!(html.contains("zip.file('manifest.json'"));
    assert!(html.contains("package_format_version: '3dmk-package-v1'"));
    assert!(html.contains("analysis/scene-analysis.json"));
    assert!(html.contains("transforms/history.json"));
    assert!(html.contains("review/room-plan.json"));
    assert!(html.contains("review/measurement-objects.json"));
    assert!(html.contains("const rememberTextureAsset ="));
    assert!(html.contains("pointGeometry.userData.texture = sourceTexture || null"));
    assert!(html.contains("meshGeometry.userData.texture = sourceTexture || null"));
    assert!(html.contains("Saved ${packaged.filename} with geometry, textures, reference photos, analysis, room-plan review, and measurements when available."));
    assert!(html.contains("Exported ${asset.filename} as a raw 3D model."));
    assert!(html.contains("scene_analysis_context"));
    assert!(html.contains("mesh_smoothing"));
    assert!(html.contains("model_floorplan_recognition"));
    assert!(html.contains("scene_metadata"));
    assert!(html.contains("id=\"helpDrawer\""));
    assert!(html.contains("id=\"helpToggleBtn\""));
    assert!(html.contains("id=\"helpPinBtn\""));
    assert!(html.contains("id=\"measureUnitsSelect\""));
    assert!(html.contains("Measurement display units"));
    assert!(html.contains("saved as its own measurement object"));
    assert!(html.contains("localStorage.getItem(HELP_DRAWER_PIN_KEY)"));
    assert!(html.contains("raw_outer_boundary"));
    assert!(html.contains("outer_walls"));
    assert!(html.contains("outer_corners"));
    assert!(html.contains("Load a mesh to build a room plan."));
    assert!(html.contains("id=\"roomPlanShowWalls\""));
    assert!(html.contains("id=\"roomPlanShowCorners\""));
    assert!(html.contains("id=\"roomPlanShowRooms\""));
    assert!(html.contains("id=\"roomPlanShowRaw\""));
    assert!(html.contains("id=\"clearRoomPlanBtn\""));
    assert!(html.contains("function updateRoomPlanLayerVisibility"));
    assert!(html.contains("function clearFloorplanLayoutOverlay"));
    assert!(html.contains("renderFloorplanLayout(data.layout, { replaceScene: false, cutHeight: Number(data.cut_height) || 0 })"));
    assert!(!html.contains("Floorplan image → STEP"));
    assert!(!html.contains("Load a model, point cloud, or floorplan image"));
    assert!(html.contains("function countLayoutWalls"));
    assert!(html.contains("function countLayoutCorners"));
    assert!(html.contains("sceneAnalysisOverlayGroup"));
    assert!(html.contains("const getAccordionHeader = item =>"));
    assert!(html.contains("function openAccordionPath"));
    assert!(html.contains("function runActionTarget(button)"));
    assert!(html.contains(".accordion-item.active > .accordion-body { display: block; }"));
    assert!(html.contains(".accordion-item.active > .accordion-header::after { content: '−'; }"));
    assert!(html.contains("body.sidebar-open.help-open #historyControls"));
    assert!(html.contains("body.sidebar-open.view-open #historyControls"));
    assert!(!html.contains("handlePrecisionWheel"));
    assert!(!html.contains("function handleTrackpadPan"));
    assert!(!html.contains("id=\"navigationProfile\""));
    assert!(!html.contains("localStorage.getItem('3dmk-navigation-profile'"));
    assert!(!html.contains("localStorage.setItem('3dmk-navigation-profile'"));
    assert!(html.contains("localStorage.removeItem('3dmk-navigation-profile')"));
    assert!(html.contains("controls.mouseButtons.LEFT = THREE.MOUSE.ROTATE"));
    assert!(html.contains("controls.mouseButtons.RIGHT = THREE.MOUSE.PAN"));
    assert!(html.contains("controls.touches.TWO = THREE.TOUCH.DOLLY_PAN"));
    assert!(html.contains("OrbitControls mouse mapping contract failed"));
    assert!(html.contains("OrbitControls touch mapping contract failed"));
    assert!(!html.contains("Native pinch zoom contract failed"));
    assert!(!html.contains(".usdz"), "USDZ is not supported by a loader");
    assert!(!html.to_ascii_lowercase().contains("splat"));
    assert!(!html.to_ascii_lowercase().contains("voxelize"));
    assert!(!html.to_ascii_lowercase().contains("convex mesh"));
}
