use spatial_types::{Point3, SpatialError, Vec3};
use std::{collections::BTreeMap, fs, path::Path};
#[derive(Debug,Clone,Copy,PartialEq)]pub struct PointRecord{pub position:Point3,pub rgb:Option<[u8;3]>}
#[derive(Debug,Clone,PartialEq)]pub struct PointCloud{pub points:Vec<PointRecord>}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct CloudSummary{pub count:usize,pub min:Point3,pub max:Point3,pub centroid:Point3}
impl PointCloud{
pub fn from_path(path:&Path)->Result<Self,SpatialError>{let ext=path.extension().and_then(|s|s.to_str()).unwrap_or("").to_ascii_lowercase();let text=fs::read_to_string(path)?;match ext.as_str(){"ply"=>Self::from_ascii_ply(&text),"pts"=>Self::from_pts(&text),"ptx"=>Self::from_ptx(&text),"obj"=>Self::from_obj_vertices(&text),"stl"=>Self::from_ascii_stl_vertices(&text),"off"=>Self::from_off_vertices(&text),"xyz"|"xyzrgb"|"csv"|"txt"|"asc"=>Self::from_xyz_text(&text),_=>Err(SpatialError::Parse{line:0,message:format!("unsupported native point import extension '.{ext}'")})}}
pub fn from_xyz_text(text:&str)->Result<Self,SpatialError>{parse_rows(text,false)}
pub fn from_pts(text:&str)->Result<Self,SpatialError>{let mut lines=text.lines();let first=lines.next().unwrap_or("").trim();let body=if first.parse::<usize>().is_ok(){lines.collect::<Vec<_>>().join("\n")}else{text.into()};parse_rows(&body,false)}
pub fn from_ptx(text:&str)->Result<Self,SpatialError>{let lines:Vec<_>=text.lines().collect();if lines.len()<10{return Err(err(1,"PTX header is incomplete"));}let columns=lines[0].trim().parse::<usize>().map_err(|_|err(1,"invalid PTX columns"))?;let rows=lines[1].trim().parse::<usize>().map_err(|_|err(2,"invalid PTX rows"))?;let body=lines.iter().skip(10).take(columns*rows).copied().collect::<Vec<_>>().join("\n");parse_rows(&body,true)}
pub fn from_obj_vertices(text:&str)->Result<Self,SpatialError>{let body=text.lines().filter_map(|l|l.trim().strip_prefix("v ")).collect::<Vec<_>>().join("\n");Self::from_xyz_text(&body)}
pub fn from_ascii_stl_vertices(text:&str)->Result<Self,SpatialError>{let body=text.lines().filter_map(|l|l.trim().strip_prefix("vertex ")).collect::<Vec<_>>().join("\n");Self::from_xyz_text(&body)}
pub fn from_off_vertices(text:&str)->Result<Self,SpatialError>{let mut lines=text.lines().map(str::trim).filter(|x|!x.is_empty()&&!x.starts_with('#'));if lines.next()!=Some("OFF"){return Err(err(1,"missing OFF signature"));}let counts:Vec<_>=lines.next().ok_or_else(||err(2,"missing OFF counts"))?.split_whitespace().collect();let n=counts.first().ok_or_else(||err(2,"missing OFF vertex count"))?.parse::<usize>().map_err(|_|err(2,"invalid OFF vertex count"))?;let body=lines.take(n).collect::<Vec<_>>().join("\n");Self::from_xyz_text(&body)}
pub fn from_ascii_ply(text:&str)->Result<Self,SpatialError>{let lines:Vec<_>=text.lines().collect();if lines.first().copied()!=Some("ply"){return Err(err(1,"missing ply signature"));}if !lines.contains(&"format ascii 1.0"){return Err(err(2,"only ASCII PLY is natively supported"));}let count=lines.iter().find_map(|l|l.strip_prefix("element vertex ").and_then(|v|v.parse().ok())).ok_or_else(||err(2,"missing vertex element"))?;let end=lines.iter().position(|l|*l=="end_header").ok_or_else(||err(2,"missing end_header"))?+1;let body=lines.iter().skip(end).take(count).copied().collect::<Vec<_>>().join("\n");let c=Self::from_xyz_text(&body)?;if c.points.len()!=count{return Err(err(end,"vertex count mismatch"));}Ok(c)}
pub fn summary(&self)->Result<CloudSummary,SpatialError>{let first=self.points.first().ok_or(SpatialError::Degenerate("point cloud is empty"))?.position.0;let(mut min,mut max,mut sum)=(first,first,Vec3::ZERO);for p in &self.points{let v=p.position.0;min.x=min.x.min(v.x);min.y=min.y.min(v.y);min.z=min.z.min(v.z);max.x=max.x.max(v.x);max.y=max.y.max(v.y);max.z=max.z.max(v.z);sum=sum.add(v);}let n=self.points.len()as f64;Ok(CloudSummary{count:self.points.len(),min:Point3(min),max:Point3(max),centroid:Point3(sum.scale(1./n))})}
pub fn voxel_decimate(&self,size:f64)->Result<Self,SpatialError>{if !size.is_finite()||size<=0.0{return Err(SpatialError::Degenerate("voxel size must be positive"));}let mut bins:BTreeMap<(i64,i64,i64),(Vec3,usize,Option<[u64;3]>,usize)>=BTreeMap::new();for p in &self.points{let v=p.position.0;let k=((v.x/size).floor()as i64,(v.y/size).floor()as i64,(v.z/size).floor()as i64);let e=bins.entry(k).or_insert((Vec3::ZERO,0,Some([0;3]),0));e.0=e.0.add(v);e.1+=1;if let Some(c)=p.rgb{if let Some(s)=&mut e.2{s[0]+=c[0]as u64;s[1]+=c[1]as u64;s[2]+=c[2]as u64;}e.3+=1}else{e.2=None;}}let points=bins.into_values().map(|(sum,n,cs,cn)|PointRecord{position:Point3(sum.scale(1./n as f64)),rgb:cs.filter(|_|cn==n).map(|s|[(s[0]/n as u64)as u8,(s[1]/n as u64)as u8,(s[2]/n as u64)as u8])}).collect();Ok(Self{points})}
pub fn to_xyz(&self)->String{self.points.iter().map(|p|{let v=p.position.0;match p.rgb{Some(c)=>format!("{:.9} {:.9} {:.9} {} {} {}\n",v.x,v.y,v.z,c[0],c[1],c[2]),None=>format!("{:.9} {:.9} {:.9}\n",v.x,v.y,v.z)}}).collect()}
}
fn parse_rows(text:&str,ptx:bool)->Result<PointCloud,SpatialError>{let mut points=Vec::new();for(i,line)in text.lines().enumerate(){let t=line.trim();if t.is_empty()||t.starts_with('#'){continue;}let c:Vec<_>=t.split(|x:char|x==','||x.is_whitespace()).filter(|s|!s.is_empty()).collect();if c.len()<3{return Err(err(i+1,"expected x y z"));}let n=|k:usize|c[k].parse::<f64>().map_err(|_|err(i+1,"invalid coordinate"));let position=Point3::new(n(0)?,n(1)?,n(2)?)?;let color_start=if ptx&&c.len()>=7{4}else{3};let rgb=if c.len()>=color_start+3{Some([u8v(c[color_start],i+1)?,u8v(c[color_start+1],i+1)?,u8v(c[color_start+2],i+1)?])}else{None};points.push(PointRecord{position,rgb});}if points.is_empty(){return Err(SpatialError::Degenerate("point cloud is empty"));}Ok(PointCloud{points})}
fn u8v(s:&str,l:usize)->Result<u8,SpatialError>{s.parse().map_err(|_|err(l,"invalid RGB value"))}fn err(line:usize,m:&str)->SpatialError{SpatialError::Parse{line,message:m.into()}}
#[cfg(test)]mod tests{use super::*;#[test]fn parses_pts_count_header(){let c=PointCloud::from_pts("2\n0 0 0\n1 2 3\n").unwrap();assert_eq!(c.points.len(),2);}#[test]fn parses_obj_vertices(){assert_eq!(PointCloud::from_obj_vertices("v 0 0 0\nv 1 2 3\nf 1 2 2\n").unwrap().points.len(),2);}#[test]fn decimation_is_deterministic(){let c=PointCloud::from_xyz_text("0 0 0\n0.1 0 0\n2 0 0\n").unwrap();assert_eq!(c.voxel_decimate(1.).unwrap().points.len(),2);}}
