use serde_json::json;

use crate::{ConversionError, ErrorCode, OutputFormat};

#[derive(Clone, Debug)]
pub struct Mesh {
    pub name: String,
    pub positions: Vec<[f32; 3]>,
    pub normals: Vec<[f32; 3]>,
    pub indices: Vec<u32>,
}

impl Mesh {
    pub fn new(
        name: impl Into<String>,
        positions: Vec<[f32; 3]>,
        normals: Vec<[f32; 3]>,
        indices: Vec<u32>,
    ) -> Self {
        Self {
            name: name.into(),
            positions,
            normals,
            indices,
        }
    }
    fn validate(&self) -> Result<(), ConversionError> {
        if self.positions.is_empty()
            || self.positions.len() != self.normals.len()
            || self.indices.len() % 3 != 0
            || self
                .indices
                .iter()
                .any(|index| *index as usize >= self.positions.len())
            || self
                .positions
                .iter()
                .chain(self.normals.iter())
                .flatten()
                .any(|value| !value.is_finite())
        {
            Err(ConversionError::new(
                ErrorCode::ValidationFailed,
                "Mesh contains invalid geometry",
                None,
                None,
            ))
        } else {
            Ok(())
        }
    }
}

pub fn export_mesh(meshes: &[Mesh], format: OutputFormat) -> Result<Vec<u8>, ConversionError> {
    for mesh in meshes {
        mesh.validate()?;
    }
    match format {
        OutputFormat::Obj => Ok(obj(meshes).into_bytes()),
        OutputFormat::Ply => Ok(ply(meshes).into_bytes()),
        OutputFormat::Stl => Ok(stl(meshes)),
        OutputFormat::Glb => glb(meshes),
    }
}

fn obj(meshes: &[Mesh]) -> String {
    let mut text = String::from("# Oilwell Converter\n");
    let mut offset = 1;
    for mesh in meshes {
        text.push_str(&format!(
            "o {}\n",
            mesh.name.replace(char::is_whitespace, "_")
        ));
        for point in &mesh.positions {
            text.push_str(&format!("v {} {} {}\n", point[0], point[1], point[2]));
        }
        for normal in &mesh.normals {
            text.push_str(&format!("vn {} {} {}\n", normal[0], normal[1], normal[2]));
        }
        for face in mesh.indices.chunks_exact(3) {
            text.push_str(&format!(
                "f {}//{} {}//{} {}//{}\n",
                face[0] + offset,
                face[0] + offset,
                face[1] + offset,
                face[1] + offset,
                face[2] + offset,
                face[2] + offset
            ));
        }
        offset += mesh.positions.len() as u32;
    }
    text
}
fn ply(meshes: &[Mesh]) -> String {
    let vertices: usize = meshes.iter().map(|mesh| mesh.positions.len()).sum();
    let faces: usize = meshes.iter().map(|mesh| mesh.indices.len() / 3).sum();
    let mut text = format!("ply\nformat ascii 1.0\ncomment Generated by Oilwell Converter\nelement vertex {vertices}\nproperty float x\nproperty float y\nproperty float z\nproperty float nx\nproperty float ny\nproperty float nz\nelement face {faces}\nproperty list uchar int vertex_indices\nend_header\n");
    let mut offset = 0u32;
    for mesh in meshes {
        for (point, normal) in mesh.positions.iter().zip(&mesh.normals) {
            text.push_str(&format!(
                "{} {} {} {} {} {}\n",
                point[0], point[1], point[2], normal[0], normal[1], normal[2]
            ));
        }
        for face in mesh.indices.chunks_exact(3) {
            text.push_str(&format!(
                "3 {} {} {}\n",
                face[0] + offset,
                face[1] + offset,
                face[2] + offset
            ));
        }
        offset += mesh.positions.len() as u32;
    }
    text
}
fn stl(meshes: &[Mesh]) -> Vec<u8> {
    let count: usize = meshes.iter().map(|mesh| mesh.indices.len() / 3).sum();
    let mut bytes = vec![0u8; 84 + count * 50];
    let header = b"Generated by Oilwell Converter";
    bytes[..header.len()].copy_from_slice(header);
    bytes[80..84].copy_from_slice(&(count as u32).to_le_bytes());
    let mut at = 84;
    for mesh in meshes {
        for face in mesh.indices.chunks_exact(3) {
            let p = [
                mesh.positions[face[0] as usize],
                mesh.positions[face[1] as usize],
                mesh.positions[face[2] as usize],
            ];
            let normal = normal(p[0], p[1], p[2]);
            for value in normal.into_iter().chain(p.into_iter().flatten()) {
                bytes[at..at + 4].copy_from_slice(&value.to_le_bytes());
                at += 4;
            }
            at += 2;
        }
    }
    bytes
}
fn normal(a: [f32; 3], b: [f32; 3], c: [f32; 3]) -> [f32; 3] {
    let u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
    let v = [c[0] - a[0], c[1] - a[1], c[2] - a[2]];
    let n = [
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    ];
    let l = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt();
    if l > 0.0 {
        [n[0] / l, n[1] / l, n[2] / l]
    } else {
        [0.0, 0.0, 0.0]
    }
}
fn glb(meshes: &[Mesh]) -> Result<Vec<u8>, ConversionError> {
    let mut binary = Vec::new();
    let mut views = Vec::new();
    let mut accessors = Vec::new();
    let mut primitives = Vec::new();
    for mesh in meshes {
        let position_offset = align(&mut binary);
        for point in &mesh.positions {
            for v in point {
                binary.extend(v.to_le_bytes());
            }
        }
        let position_view = views.len();
        views.push(json!({"buffer":0,"byteOffset":position_offset,"byteLength":mesh.positions.len()*12,"target":34962}));
        let min = [0, 1, 2].map(|axis| {
            mesh.positions
                .iter()
                .map(|p| p[axis])
                .fold(f32::INFINITY, f32::min)
        });
        let max = [0, 1, 2].map(|axis| {
            mesh.positions
                .iter()
                .map(|p| p[axis])
                .fold(f32::NEG_INFINITY, f32::max)
        });
        let position_accessor = accessors.len();
        accessors.push(json!({"bufferView":position_view,"componentType":5126,"count":mesh.positions.len(),"type":"VEC3","min":min,"max":max}));
        let normal_offset = align(&mut binary);
        for point in &mesh.normals {
            for v in point {
                binary.extend(v.to_le_bytes());
            }
        }
        let normal_view = views.len();
        views.push(json!({"buffer":0,"byteOffset":normal_offset,"byteLength":mesh.normals.len()*12,"target":34962}));
        let normal_accessor = accessors.len();
        accessors.push(json!({"bufferView":normal_view,"componentType":5126,"count":mesh.normals.len(),"type":"VEC3"}));
        let index_offset = align(&mut binary);
        for index in &mesh.indices {
            binary.extend(index.to_le_bytes());
        }
        let index_view = views.len();
        views.push(json!({"buffer":0,"byteOffset":index_offset,"byteLength":mesh.indices.len()*4,"target":34963}));
        let index_accessor = accessors.len();
        accessors.push(json!({"bufferView":index_view,"componentType":5125,"count":mesh.indices.len(),"type":"SCALAR","min":[0],"max":[mesh.indices.iter().copied().max().unwrap_or(0)]}));
        primitives.push(json!({"name":mesh.name,"primitives":[{"attributes":{"POSITION":position_accessor,"NORMAL":normal_accessor},"indices":index_accessor}]}));
    }
    let nodes = (0..meshes.len())
        .map(|i| json!({"mesh":i,"name":meshes[i].name}))
        .collect::<Vec<_>>();
    let mut scene_nodes = vec![
        json!({"name":"Oilwell Pad","rotation":[-0.70710677,0.0,0.0,0.70710677],"extras":{"source_coordinate_system":"cad_z_up"},"children":(1..=meshes.len()).collect::<Vec<_>>() }),
    ];
    scene_nodes.extend(nodes);
    let doc = json!({"asset":{"version":"2.0","generator":"Oilwell Converter"},"scene":0,"scenes":[{"nodes":[0]}],"nodes":scene_nodes,"meshes":primitives,"buffers":[{"byteLength":binary.len()}],"bufferViews":views,"accessors":accessors});
    let mut json_bytes = serde_json::to_vec(&doc).map_err(|_| {
        ConversionError::new(
            ErrorCode::WriteFailed,
            "Unable to serialize GLB",
            None,
            None,
        )
    })?;
    while json_bytes.len() % 4 != 0 {
        json_bytes.push(b' ');
    }
    align(&mut binary);
    let total = 12 + 8 + json_bytes.len() + 8 + binary.len();
    let mut out = Vec::with_capacity(total);
    out.extend(0x46546c67u32.to_le_bytes());
    out.extend(2u32.to_le_bytes());
    out.extend((total as u32).to_le_bytes());
    out.extend((json_bytes.len() as u32).to_le_bytes());
    out.extend(0x4e4f534au32.to_le_bytes());
    out.extend(json_bytes);
    out.extend((binary.len() as u32).to_le_bytes());
    out.extend(0x004e4942u32.to_le_bytes());
    out.extend(binary);
    Ok(out)
}
fn align(bytes: &mut Vec<u8>) -> usize {
    while bytes.len() % 4 != 0 {
        bytes.push(0);
    }
    bytes.len()
}
